# Generated by Django 4.1.7 on 2023-03-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrawnNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='draw numbers', max_length=10, null=True)),
                ('monday', models.CharField(max_length=3)),
                ('tuesday', models.CharField(max_length=3)),
                ('wednesday', models.CharField(max_length=3)),
                ('thursday', models.CharField(max_length=3)),
                ('friday', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='draw numbers', max_length=10, null=True)),
                ('monday', models.CharField(max_length=3)),
                ('tuesday', models.CharField(max_length=3)),
                ('wednesday', models.CharField(max_length=3)),
                ('thursdayday', models.CharField(max_length=3)),
                ('friday', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
